<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <EnableHarmony>true</EnableHarmony>
    <NoWarn>8632</NoWarn>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>NpcTrackerMod</RootNamespace>
    <AssemblyName>NpcTrackerMod</AssemblyName>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

</Project>